blog/app/urls.py
from . import views
from django.urls import path

urlpatterns = [
	path('', views.BlogPostList.as_view(), name='home'),
	path('<slug:slug>/', views.BlogPostDetail.as_view(), name='post_detail'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('app.urls')),
]

blog/app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

PUBLISHED = (
	(0, 'Draft'),
	(1, 'Published')
)


class BlogPost(models.Model):

	title = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(max_length=200, unique=True)
	author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='blog_posts')
	created_on = models.DateTimeField(auto_now_add=True)
	updated_on = models.DateTimeField(auto_now=True)
	content = models.TextField()
	status = models.IntegerField(choices=PUBLISHED, default=0)

	class Meta:
		# Order by latest created
		ordering = ['-created_on']

	def __str__(self):
		# Use the title as the string representation
		return(self.title)

blog/app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import BlogPost

# Create your views here.
class BlogPostList(generic.ListView):
	queryset = BlogPost.objects.filter(status=1).order_by('-created_on')
	template_name = 'index.html'

class BlogPostDetail(generic.DetailView):
	model = BlogPost
	template_name = 'post_detail.html'

blog/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: sans-serif, "Helvetica Neue", "Lucida Grande", Arial;
            font-size: 18px;
            background-color: #f0f0f0;
        }
        .shadow {
            box-shadow: 4pt 4pt 4pt 4pt #e0e0e0;
        }

    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Blog</p>
        </footer>
    </body>
</html>

blog/templates/index.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: sans-serif, "Helvetica Neue", "Lucida Grande", Arial;
        font-size: 18px;
        background-color: #f0f0f0;
    }
        
    .card {
        box-shadow: 0 8px 16px #e0e0e0;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col mt-3 left">
            {% for post in blogpost_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

blog/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ blogpost.author }} | {{ blogpost.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}